title: Chad Sheets | FreeCodeCamp
email: hello@chadsheets.com
description: Chad Sheets (cjsheets) - FreeCodeCamp Solutions
#url: https://chadsheets.com/fcc.chadsheets.com/
url: /

sass:
  sass_dir: _sass
  style: compressed

# Build settings
markdown: kramdown
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
