title: Chad Sheets | FreeCodeCamp
email: hello@chadsheets.com
description: Chad Sheets (cjsheets) - FreeCodeCamp Solutions
url: ''

sass:
  sass_dir: _sass
  style: compressed

# Build settings
markdown: kramdown
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
